CREATE TABLE `BUILDING` (
    `BUILDING_ID` int NOT NULL AUTO_INCREMENT,
    `DEPT_ID` int NOT NULL, -- Foreign key to DEPARTMENT table
    `BUILDING_NAME` varchar(45) DEFAULT NULL,
    `BUILDING_ADDRESS` varchar(45) DEFAULT NULL,
    PRIMARY KEY (`BUILDING_ID`),
    FOREIGN KEY (`DEPT_ID`) REFERENCES DEPARTMENT(`DEPT_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
