CREATE TABLE `DEPARTMENT` (
    `DEPT_ID` int NOT NULL AUTO_INCREMENT,
    `DEPT_NAME` varchar(60) DEFAULT NULL,
    PRIMARY KEY (`DEPT_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
