CREATE TABLE `PROFESSOR` (
  `PROF_ID` int NOT NULL AUTO_INCREMENT,
  `PERSON_ID` int NOT NULL, -- Can't be NULL (?), the professor must be a person -- Foreign key to PERSON table
  `DEPT_ID` int DEFAULT NULL, -- Foreign key to DEPARTMENT table
  `OFFICE_NUM` int DEFAULT NULL,
  `BUILDING_ID` int DEFAULT NULL, -- Foreign key to BUILDING table
  PRIMARY KEY (`PROF_ID`),
  FOREIGN KEY (`PERSON_ID`) REFERENCES PERSON(`PERSON_ID`),
  FOREIGN KEY (`BUILDING_ID`) REFERENCES BUILDING(`BUILDING_ID`),
  FOREIGN KEY (`DEPT_ID`) REFERENCES DEPARTMENT(`DEPT_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
